### ISSUE TITLE
Less total expression after saver?

### ISSUE THREAD

**Issue by ericvon11** [mohuangx/SAVER#14]
I've run saver with 43k cells, on a subset of genes expressed in at least 100 cells with at least 100 copies (in the entire dataset). Somehow, I'm finding that the sum of my output matrix in saver$estimate is lower than my input by several tens of thousands. I'm using size.factor =1 because I've already normalized my data.

```
saver1 = saver(x = data, do.fast = TRUE, size.factor = 1, pred.genes = gene.indices[1:2500], pred.genes.only = T, ncores = 16)

> sum(saver1$estimate) - sum(data[gene.indices[1:2500],])
[1] -86580.29
```
I had understood that SAVER would impute values where they don't already exist or add to what already exists, but this appears to have lowered my overall expression. Either that, or what I suspect is more likely is that the mean library size-normalization is coming into play.

Here's a randomly selected cell:
```
> saver1$estimate[1:10,6197 ]
   Xkr4  Gm1992     Rp1  Mrpl15 Gm37988   Tcea1   Rgs20 Atp6v1h   Oprk1  Rb1cc1 
  2.031   0.105   0.004   0.083   0.004   0.095   0.261   0.388   0.040   0.767 
> data[gene.indices[1:10],6197 ]
    Xkr4   Gm1992      Rp1   Mrpl15  Gm37988    Tcea1    Rgs20  Atp6v1h    Oprk1   Rb1cc1 
3.139104 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 1.543411 
```
Again, it looks like it imputed new values where there were none, but the genes that already had high expression are now lowered.

I've confirmed the cell names match up and both datasets contain the same amount of columns/cells.

Any thoughts?

**Comment by mohuangx** [comment]
I just checked this in two datasets and found the reverse behavior - the mean of the SAVER estimates was larger than the raw data but only by about 0.001.

In your case, the reason might be due to the specific genes you are selecting. One of the effects of SAVER is that it shrinks the raw expression values towards predicted values, which tends to be less variable than the raw expression values. As a result, for a gene, the estimates for low expression cells will be higher than the raw values while the estimates for high expression cells will be lower than the raw values. I suspect for the genes you're looking at, the shrinkage has a greater effect on the cells with high expression, resulting in the behavior you see. However, if you look at the mean of the differences instead of the sum, you see that the difference is less than 0.001. In all, I don't think the overall magnitude of the SAVER estimates vs. the original dataset matters too much for downstream analysis.

Let me know if you have any additional questions.

**Comment by ericvon11** [comment]
Hi Mo,

Thanks for the detailed response. I see. So it seems saver adjusts expression mostly by squashing too high and raising too low values in order to reduce noise. Good to know. That probably reflects the true biology better. I'll let you know if I have any more questions.

Best,
Eric
