### ISSUE TITLE
Any speed optimization planned for large datasets?

### ISSUE THREAD

**Issue by FloWuenne** [mohuangx/SAVER#2]
Hi Mohuan,

great talk at ASHG this year! I am currently running SAVER on some of our Drop-seq datasets and I was wondering whether there are any other tips to improve runtime besides multicore usage via doParallel? It is still quite slow even when using multiple cores on large data. I am currently running 10 000 cells and it takes about 2 days using 12 cores. 

Anything planned to speed up the imputation algorithm?
Sorry for submitting an issue for this, was the easiest way to get in contact. 

All the best for SAVER, I really like the code! 

Best,

Florian

**Comment by mohuangx** [comment]
Hi Florian,

Thanks for trying out our code! We're in the process of speeding it up, which will be implemented in the next release soon.

As for right now, you could try adjusting the nzero parameter to a higher value (like 100 or more). The default is a pretty conservative value of 10 cells with non-zero expression but the prediction algorithm will be unlikely to help much for genes that have non-zero expression in less than 100 or so cells since your dataset contains 10,000. 

Best,
Mo

**Comment by mohuangx** [comment]
Hi Florian,

Sorry for the delay, but we have just released a faster version of SAVER, which should be about 20-30 times faster than before. Hopefully you'll be able to give it a try!

Best,
Mo
