### ISSUE TITLE
SAVER vs Seurat normalization

### ISSUE THREAD

**Issue by igordot** [mohuangx/SAVER#21]
In a previous discussion (https://github.com/mohuangx/SAVER/issues/18), it was suggested to use SAVER estimates as the raw counts for Seurat:
```
data.saver <- saver(data, estimates.only = TRUE)
seurat.obj <- CreateSeuratObject(raw.data = data.saver)
seurat.obj <- NormalizeData(seurat.obj)
```
The SAVER estimates are library size normalized (the column sums are not equal). When you run `NormalizeData()`, they will get normalized again to a constant number (by default, column sums are 10k). I assume the SAVER normalization is preferred by the SAVER authors. Then shouldn't extra Seurat normalization be skipped?

**Comment by mohuangx** [comment]
That's a good point. It would make more sense to directly set the `@data` slot of the Seurat object with the library size normalized SAVER output. I'm not sure how much of a difference it would make for downstream results since the SAVER estimates should have similar column sums.

**Comment by igordot** [comment]
I am not sure how much of a difference it would make for downstream analysis.

In the one dataset I checked, the SAVER estimates column sums were 7500-9500, so there is substantial variability. However, that might be due to just a few genes.

Regardless, thank you for clarifying.

**Comment by ravipatel4** [comment]
I also see a range of "column sums" in SAVER estimates instead of a constant value. I am not sure if that is how it should be.

I use the SAVER estimates as input in Seurat, treating them as library normalized data. I skip Seurat's normalization step, but instead I just log-transform the `@data` slot, like this: `obj@data = log(obj@data+1)`.

**Comment by mohuangx** [comment]
Seeing SAVER results with a range of column sums is expected as there is no constraint on the output.. However, a library size normalization is performed within the method itself so the output is in some sense normalized. The resulting discrepancy in column sums could be natural variation or simply noise.

@ravipatel4 Thanks for clarifying that you have to take the log, but I'm not sure if you necessarily need the +1 or not since the SAVER output should be strictly greater than zero. I haven't tested whether just taking the log without adding a constant would cause different downstream results.

**Comment by ravipatel4** [comment]
Thanks @mohuangx , for the clarification about variable column sums.
Regarding normalization in Seurat, based on their code it seems that they perform counts per 10k normalization and log-transform the data after adding pseudo-count of 1. Hence, I take a log of SAVER estimates. But I agree I don't need to +1, and probably I shouldn't. Thanks for pointing that out.

**Comment by ravipatel4** [comment]
@mohuangx, I remember why I used +1. There are many values below 1 in SAVER estimates, which turn into negative values post-log-transformation. Seurat doesn't like that and it fails with errors. Adding pseudo-count of 1 prevents Seurat from breaking. I am not sure if there is a way to prevent Seurat from breaking when it encounters negative values in `@data` slot.

**Comment by Puriney** [comment]
No. Probably there is no way to prevent Seurat from breaking if `@data` slot has negative values. This is because by defualt Seurat's NormalizeData performs log1p, which means Seurat always assume the normalized data matrix has non-negative values.

See the line 120: https://github.com/satijalab/seurat/blob/94343c4fdb35a3a1e7a7e14d4a0bb0cec657075c/src/data_manipulation.cpp#L114-L124
