### ISSUE TITLE
Saver in docker

### ISSUE THREAD

**Issue by alessandriLuca** [mohuangx/SAVER#27]
Good morning, I installed SAVER in a docker container and i tried to RUN SAVER from there but, it give me an error about the ssh connection . Using this command

` mm.saver <- saver(mainMatrix, ncores = ncores,estimates.only = TRUE) `
This is the output : 

> ssh: connect to host 0.0.0.4 port 22: Connection timed out

Using only one core i have the same error but with different last host number. 
You can find the docker container downloading repbioinfo/saver . If you try to run saver here you will see the error. 
Thank you for your support 

Best

Luca

**Comment by mohuangx** [comment]
Hi, sorry for the late response. I don't have much experience with Docker so I can't say with certainty but it seems like it might be an issue with the Docker container since I haven't encountered this issue before. Can you try running the example code in the `saver` function documentation to see if it works?

**Comment by alessandriLuca** [comment]
Hi, dont worry for the late answer, these are hard times hehe. By the way i found out the problem, i was giving to saver the ncores variable as string since i made a script and I didn't convert it in numeric before to run the saver funciton. Now works perfectly! THank you ;)
