### ISSUE TITLE
missing entries in NAMESPACE file

### ISSUE THREAD

**Issue by bvieth** [mohuangx/SAVER#3]
Dear Mo,

I would like to implement SAVER in my simulation tool. The code runs fine when I explicitly load all libraries but once I include the main saver function, I get the following error:
`Error in foreach::foreach(xit = iterators::iter(x[lasso.genes, ], by = "row"),  : 
  could not find function "%dopar%"`

The reason is that the functions are not stated in the NAMESPACE file (specifically foreach). May I suggest that you include the packages and functions with `#' @importFrom` calls in your R code files?

Kind regards
Beate

**Comment by mohuangx** [comment]
Hi Beate,

Sorry for the late response. Seems that I don't get notifications for issues.

Thanks for bringing this up to my attention. It seems that using @importFrom is [no longer recommended](https://cran.r-project.org/web/packages/roxygen2/vignettes/namespace.html), but I have imported the foreach package in the saver function since I think the problem is %dopar%. You can find the change in the most recent commit.

Mo

**Comment by mohuangx** [comment]
Hi Beate,

We have just implemented a faster version of SAVER, which includes an import call for `foreach`. Hope you can try it out!

Best,
Mo
