### ISSUE TITLE
Subsetting Dataset

### ISSUE THREAD

**Issue by sylvia-science** [mohuangx/SAVER#40]
Hello,

If I'm particularly interested in a subset of cells in my dataset, is it valid to run SAVER on just that subset? 

Furthermore, I'm working on a dataset comprised from many different scRNA sources where I suspect batch effects may be relevant. Would it be a good idea to split my SAVER runs to be on each source instead of running on data combined from all sources?

Thank you!

**Comment by mohuangx** [comment]
Hi,

I would recommend running SAVER on the entire dataset so that the prediction is performed on more cells and then look at the subset of the SAVER output but if computation is an issue, it's perfectly fine to run SAVER on the subset of cells too.

I agree that it's probably better to split the SAVER runs and then possibly batch correct. This way, SAVER won't be picking up on differences between sources in performing the prediction.

**Comment by sylvia-science** [comment]
Thank you for the fast response!
